# Generated by Django 4.2.2 on 2023-08-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagenitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
        migrations.DeleteModel(
            name='ImagenItem',
        ),
    ]
