# Generated by Django 4.2.2 on 2023-11-30 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_user_id_carrito_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='user',
        ),
        migrations.AddField(
            model_name='myuser',
            name='carrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.carrito'),
        ),
    ]
